
repos:
    -
        repo: 'https://github.com/pre-commit/pre-commit-hooks'
        rev: v2.4.0
        hooks:
            - {id: check-yaml}
            - {id: end-of-file-fixer}
            - {id: trailing-whitespace}
    -
        repo: 'https://github.com/ansible/ansible-lint.git'
        rev: v4.2.0
        hooks:
            - {id: ansible-lint, files: \.(yaml|yml)$}
    -
        repo: 'https://github.com/codespell-project/codespell.git'
        rev: v1.16.0
        hooks:
            - {id: codespell}
