---

- hosts: localhost
  become: true
  vars_files:
    - vars/main.yml
  environment:
    - PATH: /usr/local/bin:{{ ansible_env.PATH  }}
  pre_tasks:
    - name: Update repositories
      yum:
        name: '*'
        state: latest
        update_cache: true
  tasks:
    - include: tasks/users.yml
    - include: tasks/install_roles.yml
    - include: tasks/packages.yml
    - include: tasks/python3.yml
    - include: tasks/azure_cli.yml
    - include: tasks/dotfiles.yml
    - include: tasks/dev.yml
