---

- hosts: localhost
  become: true
  vars_files:
    - vars/main.yml
  pre_tasks:
    - name: Update repositories
      yum:
        name: '*'
        state: latest
        update_cache: true
    - name: Check GitHub token set
      command: '[ ! -z "$GITHUB_PAT" ]'
      register: result
      failed_when: result.rc != 0
  tasks:
    - include: tasks/users.yml
    - include: tasks/install_roles.yml
    - include: tasks/git.yml
    - include: tasks/packages.yml
    - include: tasks/python3.yml
    - include: tasks/azure_cli.yml
    - include: tasks/dotfiles.yml
    - include: tasks/dev.yml
