---

- hosts: localhost
  become: true
  pre_tasks:
    - name: Update repositories
      yum: update_cache=yes
      changed_when: False
  tasks:
    - include:
        - tasks/git.yml
        - tasks/packages.yml      

