---

- hosts: localhost
  become: true
  vars_files:
    - vars/main.yml
  environment:
    - PATH: /usr/local/bin:{{ ansible_env.PATH  }}
  tasks:
    - include: tasks/setup.yml
      tags: ['always']
    - include: tasks/users.yml
    - include: tasks/git.yml
    - include: tasks/packages.yml
    - include: tasks/python3.yml
      tags: ['python']
    - include: tasks/go.yml
      tags: ['go']
    - include: tasks/azure_cli.yml
    - include: tasks/dotfiles.yml
      tags: ['dotfiles']
    - include: tasks/dev.yml
      tags: ['dev']
    - include: tasks/all-repos.yml
      tags: ['never', 'all-repos-clone']
    - include: tasks/cleanup.yml
      tags: ['always']
