---

- name: Load GitHub access token
  include_vars:
    file: /home/{{ username }}/.ansible_vars.yml
    name: private

- name: Create all-repos.json
  template:
    src: files/all-repos.json
    dest: /home/{{ username  }}/dev/all-repos.json
    owner: '{{ username  }}'
    group: '{{ username  }}'
    mode: 0600
    backup: true

- name: Run all-repos-clone
  shell: |
    ~/.local/bin/all-repos-clone -C /home/{{ username }}/dev/all-repos.json -j0
  register: result
  changed_when: '"branch is behind" in result.stdout'
