---

- name: Create dev directory
  file:
    path: /home/{{ username }}/dev
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0740'

- name: Load GitHub access token
  include_vars:
    file: /home/{{ username }}/.ansible_vars.yml
    name: private
  tags: ['never', 'all-repos-clone']

- name: Create all-repos.json
  template:
    src: files/all-repos.json
    dest: /home/{{ username  }}/dev/all-repos.json
    owner: '{{ username  }}'
    group: '{{ username  }}'
    mode: 0600
    backup: true
  tags: ['never', 'all-repos-clone']

- name: Install all-repos
  pip:
    name: all-repos
#    executable: python3 -m pip
    extra_args: --user

- name: Run all-repos-clone
  become: true
  become_user: "{{ username }}"
  command: all-repos-clone -C /home/{{ username }}/dev/all-repos.json -j 0
  register: result
  changed_when: '"branch is behind" in result.stdout'
  tags: ['never', 'all-repos-clone']
