---

- name: Create dev directory
  file:
    path: /home/{{ username }}/dev
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0740'

# TODO(RKM 2019-12-23) Fix this - it will always result in a change at the
# moment
- name: Copy all-repos.json to dev
  copy:
    src: files/all-repos.json
    dest: /home/{{ username  }}/dev/all-repos.json
    owner: '{{ username  }}'
    group: '{{ username  }}'
    mode: 0600
    backup: true

- name: Create all-repos.json  # noqa 303
  shell: |
    sed -i "s/UN/{{ username }}/g" /home/{{ username  }}/dev/all-repos.json
    sed -i "s/PAT/{{ github_pat }}/g" /home/{{ username  }}/dev/all-repos.json
  changed_when: False

- name: Install all-repos
  become: true
  become_user: "{{ username }}"
  pip:
    name: all-repos
    executable: /usr/local/bin/pip3
    extra_args: --user

- name: Run all-repos
  become: true
  become_user: "{{ username }}"
  command: all-repos-clone -C /home/{{ username }}/dev/all-repos.json
  when: true
