
---

- name: Clone https://github.com/rkm/dotfiles
  git:
    repo: https://github.com/rkm/dotfiles
    dest: /tmp/dotfiles
    depth: 1

- name: Create combined .gitconfig
  shell: >
    cat
    /tmp/dotfiles/common/.gitconfig
    /tmp/dotfiles/linux/.gitconfig
    > /tmp/dotfiles/.gitconfig

- name: Copy common .gitconfig
  copy:
    src: /tmp/dotfiles/.gitconfig
    dest: /home/{{username}}/.gitconfig
    owner: "{{username}}"
    group: "{{username}}"
    mode: 0640
    backup: yes
