
---

- name: Clone https://github.com/rkm/dotfiles
  git:
    repo: https://github.com/rkm/dotfiles
    dest: /tmp/dotfiles
    depth: 1
    version: master
  register: result
  changed_when: result.before != result.after

- name: Create combined .gitconfig
  shell: >
    cat
    /tmp/dotfiles/common/.gitconfig
    /tmp/dotfiles/linux/.gitconfig
    > /tmp/dotfiles/.gitconfig
  changed_when: False

- name: Copy combined .gitconfig
  copy:
    src: /tmp/dotfiles/.gitconfig
    dest: /home/{{ username  }}/.gitconfig
    owner: "{{ username  }}"
    group: "{{ username  }}"
    mode: 0640
    backup: yes

- name: Copy bash dotfiles
  copy:
    src: /tmp/dotfiles/linux/{{ item  }}
    dest: /home/{{ username  }}/{{ item  }}
    owner: "{{ username  }}"
    group: "{{ username  }}"
    mode: 0640
    backup: yes
  with_items:
    - .bashrc
    - .bash_aliases
    - .inputrc
