
---

- name: Register version check
  shell: git --version | grep " 2." # noqa 303
  register: current_version
  ignore_errors: yes
  changed_when: current_version.rc != 0

- name: Remove existing git
  yum:
    name: "git*"
    state: removed
  when: current_version.rc != 0

- name: Install IUS
  yum:
    name:
      - https://centos7.iuscommunity.org/ius-release.rpm
  when: current_version.rc != 0

- name: Install git 2
  yum:
    name:
      - git2u-all
  when: current_version.rc != 0
