
---

- name: Register version check
  shell: git --version | grep " 2." # noqaa 303
  register: current_version
  ignore_errors: yes
  changed_when: current_version.rc != 0

- name: Install git 2
  yum:
    name:
      - https://centos7.iuscommunity.org/ius-release.rpm
      - git2u-all
  when: current_version.rc != 0
