
---

- name: Register version check
  shell: git --version | grep " 3."
  register: current_version

- name: Install git 2
  shell: |
    yum -y install https://centos7.iuscommunity.org/ius-release.rpm
    yum -y install git2u-all
  when: current_version.rc == 1

