---

- name: Run gantsign.golang
  include_role:
    name: gantsign.golang

- name: Install go packages
  command: /usr/local/go/bin/go get -u {{ item }}
  with_items:
    - github.com/tomnomnom/gron
  changed_when: false
