---

- name: Register version check
  shell: go --version | grep {{ go_version  }}
  register: current_version
  ignore_errors: true
  changed_when: current_version.rc != 0

- name: Install Golang
  become: true
  shell: |
    cd /usr/src
    wget -q https://dl.google.com/go/go{{ go_version }}.linux-amd64.tar.gz
    tar -C /usr/local -xzf go{{ go_version }}.linux-amd64.tar.gz
    rm go{{ go_version }}.linux-amd64.tar.gz*
  when: current_version.rc != 0

# TODO Create homedir
