---

- name: Install yum packages
  yum:
    name:
      - bzip2
      - curl
      - dkms
      - gcc
      - gdb
      - htop
      - net-tools
      - nmap
      - python-pip
      - rsync
      - screen
      - strace
      - telnet
      - vim
      - wget
      - yum-plugin-versionlock

- name: Install pip packages
  pip:
    name:
      - speedtest-cli

- name: Run geerlingguy.ntp
  include_role:
    name: geerlingguy.ntp
  when: not lookup('env', 'DOCKER')

- name: Set docker username
  set_fact:
    docker_users: ["{{ username }}"]
  when: not lookup('env', 'DOCKER')

- name: Run geerlingguy.docker
  include_role:
    name: geerlingguy.docker
  when: not lookup('env', 'DOCKER')

- name: Run geerlingguy.java
  include_role:
    name: geerlingguy.java

- name: Run geerlingguy.ruby
  include_role:
    name: geerlingguy.ruby

- name: Run rkm.dotnet_core
  include_role:
    name: rkm.dotnet_core

- name: Run andrewrothstein.go
  include_role:
    name: andrewrothstein.go
