---

- name: Install yum packages
  yum:
    name:
      - epel-release
      - vim
      - net-tools
      - htop
      - gcc
      - java-1.8.0-openjdk
      - nmap
      - wget
      - curl
      - telnet
      - python-pip

- name: Install pip packages
  pip:
    name:
      - speedtest-cli

- name: Run geerlingguy.ntp
  include_role:
    name: geerlingguy.ntp

