---

- name: Install EPEL
  yum:
    name: epel-release

- name: Install yum packages
  yum:
    name:
      - bzip2
      - curl
      - dkms
      - gcc
      - gdb
      - htop
      - net-tools
      - nmap
      - python-pip
      - rsync
      - screen
      - strace
      - telnet
      - vim
      - wget
      - yum install yum-plugin-versionlock

- name: Install pip packages
  pip:
    name:
      - speedtest-cli

# TODO: Move this to install_roles and run in loop
- name: Run geerlingguy.ntp
  include_role:
    name: geerlingguy.ntp

- name: Run geerlingguy.git
  include_role:
    name: geerlingguy.git

- name: Set docker username
  set_fact:
    docker_users: ["{{ username }}"]

- name: Run geerlingguy.docker
  include_role:
    name: geerlingguy.docker

- name: Run geerlingguy.java
  include_role:
    name: geerlingguy.java
