---

- name: Install yum packages
  yum:
    name:
      - bzip2-devel
      - curl
      - epel-release
      - gcc
      - gcc
      - gdb
      - htop
      - java-1.8.0-openjdk
      - libffi-devel
      - net-tools
      - nmap
      - openssl-devel
      - python-pip
      - rsync
      - screen
      - strace
      - telnet
      - vim
      - wget

- name: Install pip packages
  pip:
    name:
      - speedtest-cli

- name: Run geerlingguy.ntp
  include_role:
    name: geerlingguy.ntp

- name: Run geerlingguy.docker
  include_role:
    name: geerlingguy.docker

