---

- name: Install python3 build dependencies
  become: true
  yum:
    name:
      - bzip2-devel
      - libffi-devel
      - openssl-devel
      - sqlite-devel
      - xz-devel
      - uuid-devel

- name: Check existing versions
  stat:
    path: "/usr/local/bin/python{{ item[:3] }}"
  register: python_stats
  with_items: "{{ python_versions }}"

- name: Create python install scripts
  template:
    src: files/install_python.sh.j2
    dest: "{{ tempdir.path }}/install_python_{{ item.item }}.sh"
    owner: '{{ username  }}'
    group: '{{ username  }}'
    mode: 0111
  when: not item.stat.exists
  with_items: "{{ python_stats.results }}"

- name: Run python install scripts
  become: true
  script: "{{ tempdir.path }}/install_python_{{ item.item }}.sh"
  when: not item.stat.exists
  with_items: "{{ python_stats.results }}"

- name: Install pip packages
  pip:
    name:
      - speedtest-cli
    executable: "python3 -m pip"
