---

- name: Install python3 build dependencies
  become: true
  yum:
    name:
      - bzip2-devel
      - libffi-devel
      - openssl-devel
      - sqlite-devel
      - xz-devel
      - uuid-devel
  tags: ['python']

- name: Check existing versions
  stat:
    path: "/usr/local/bin/{{ item[:3] }}"
  register: python_stats
  with_items: "{{ python_versions }}"
  tags: ['python']

- name: Debug
  debug: var=python_stats
  tags: ['python']

- name: Install python versions
  become: true
  shell: |
    echo {{ item.item }}
    cd /usr/src
    wget -q https://www.python.org/ftp/python/{{ item.item }}\
    /Python-{{ item.item }}.tgz
    tar xzf Python-{{ item.item }}.tgz
    cd Python-{{ item.item }}
    ./configure --enable-optimizations
    make altinstall --exec-prefix=/usr/local
    cd ..
    rm Python-{{ item.item }}.tgz
  when: not item.stat.exists
  with_items: "{{ python_stats.results }}"
  tags: ['python']

- name: Install pip packages
  pip:
    name:
      - speedtest-cli
    executable: pip3
  tags: ['python']
