
---

- name: Register version check
  shell: python3 --version | grep {{python3_version}}
  register: current_version
  ignore_errors: yes
  environment:
    PATH:$PATH:/usr/local/bin

- name: Install python3
  shell: |
    cd /usr/src
    wget https://www.python.org/ftp/python/{{python3_version}}/Python-{{python3_version}}.tgz
    tar xzf Python-{{python3_version}}.tgz
    cd Python-{{python3_version}}
    ./configure --enable-optimizations
    make altinstall
    cd ..
    rm Python-{{python3_version}}.tgz
    ln -fs /usr/local/bin/python{{python3_version[:3]}} /usr/local/bin/python3
    ln -fs /usr/local/bin/pip{{python3_version[:3]}} /usr/local/bin/pip3
  when: current_version.rc != 0

