---

- name: Install python3 build dependencies
  become: true
  yum:
    name:
      - bzip2-devel
      - libffi-devel
      - openssl-devel
      - sqlite-devel
      - xz-devel
      - uuid-devel
  tags: ['python']

- name: Check existing versions
  stat:
    path: "/usr/local/bin/{{ item[:3] }}"
  register: python_stats
  with_items: "{{ python_versions }}"
  tags: ['python']

- name: Install python versions
  become: true
  script: files/install_python.sh.j2
  when: not item.stat.exists
  with_items: "{{ python_stats.results }}"
  tags: ['python']

- name: Install pip packages
  pip:
    name:
      - speedtest-cli
    executable: pip3
  tags: ['python']
