---

- name: Register version check
  shell: python3 --version | grep {{ python3_version  }}
  register: current_version
  ignore_errors: true
  changed_when: current_version.rc != 0

- name: Install python3 build dependencies
  become: true
  yum:
    name:
      - bzip2-devel
      - libffi-devel
      - openssl-devel
      - sqlite-devel
      - xd-devel
      - uuid-devel
  when: current_version.rc != 0

- name: Install python versions
  become: true
  shell: |
    cd /usr/src
    wget https://www.python.org/ftp/python/{{ python3_version  }}\
    /Python-{{ python3_version  }}.tgz
    tar xzf Python-{{ python3_version  }}.tgz
    cd Python-{{ python3_version  }}
    ./configure --enable-optimizations
    make altinstall --exec-prefix=/usr/local
    cd ..
    rm Python-{{ python3_version  }}.tgz
    # ln -fs /usr/local/bin/python{{ python3_version[:3]  }} \
    # /usr/local/bin/python3
    # ln -fs /usr/local/bin/pip{{ python3_version[:3]  }} /usr/local/bin/pip3
  with_items: "{{ python_versions }}"
  when: current_version.rc != 0
