
---

- name: Install python3
  shell: |
    echo ver {{python3_version.split(".")[:1]}}
    aaaaaa
    cd /usr/src
    wget https://www.python.org/ftp/python/{{python3_version}}/Python-{{python3_version}}.tgz
    tar xzf Python-{{python3_version}}.tgz
    cd Python-{{python3_version}}
    ./configure --enable-optimizations
    make altinstall
    cd ..
    rm Python-{{python3_version}}.tgz
    ln -s /usr/local/bin/python... /usr/local/bin/python3
  tags:
    - testeroni

