---

- name: Create ansible user
  user:
    name: ansible
    uid: 900
    state: present

- name: Copy sudoers files
  template:
    src: files/sudoers_user
    dest: /etc/sudoers.d/dont-prompt-{{ item }}-for-password
    owner: root
    group: root
    mode: 0440
  with_list:
    - ansible
    - "{{ username }}"
  tags:
    - testeroni
