---

- name: Converge
  hosts: all
  pre_tasks:
    - name: Install yum dependencies
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - epel-release
        - git
        - ansible
    - name: Install Galaxy dependencies
      command: ansible-galaxy install -r requirements.yml
  tasks:
    - include: ../../local.yml
